#!/usr/bin/env python3
import json
import sys

# Load batch data
with open('data-local/classify-batch-fresh-2026-07-25-49fbedf1.json', 'r') as f:
    batch = json.load(f)

batch_id = batch['batch_id']

results = {
    "batch_id": batch_id,
    "results": {}
}

classifications = {
    1351401625: {"topics": [{"node": "tv-film/animation", "confidence": 0.95}], "needs_review": False, "rationale": "Two hosts reviewing anime episodes with humor and detailed analysis.", "display_title": "Anime Out of Context", "blurb": "Humorous anime reviews with in-depth episode breakdowns."},
    1356142765: {"topics": [{"node": "comedy", "confidence": 0.9}, {"node": "history", "confidence": 0.6}], "needs_review": False, "rationale": "Comedy panel show assessing historical and animal figures.", "display_title": "Evil Genius with Russell Kane", "blurb": "Russell Kane hosts witty panel debates on whether historical figures and animals are evil or genius."},
    1358187061: {"topics": [{"node": "sports/basketball", "confidence": 0.95}], "needs_review": False, "rationale": "Daily recaps and analysis of NBA games and player moves.", "display_title": "The Athletic NBA Daily", "blurb": "Daily recap of NBA games, trades, and key stories."},
    1359664915: {"topics": [{"node": "comedy/interviews", "confidence": 0.9}, {"node": "tv-film/reviews", "confidence": 0.5}], "needs_review": False, "rationale": "Two comedians discuss pop culture, drag, and their personal lives.", "display_title": "Sibling Rivalry", "blurb": "Bob and Monét discuss pop culture and their lives with sharp comedy commentary."},
    1360304023: {"topics": [{"node": "education/self-improvement", "confidence": 0.75}, {"node": "business/management", "confidence": 0.6}], "needs_review": False, "rationale": "Financial and lifestyle advice for retirement planning and transitions.", "display_title": "The Retirement Wisdom Podcast", "blurb": "Strategies for designing fulfilling retirement and life transitions."},
    1360406263: {"topics": [{"node": "fiction/comedy", "confidence": 0.9}, {"node": "fiction/sci-fi", "confidence": 0.85}], "needs_review": False, "rationale": "Female-led sci-fi comedy drama about smugglers on fringe missions.", "display_title": "We Fix Space Junk", "blurb": "Comedy sci-fi drama following smugglers on odd jobs across the galaxy."},
    1364141623: {"topics": [{"node": "business/management", "confidence": 0.85}, {"node": "psychology", "confidence": 0.6}], "needs_review": False, "rationale": "Leadership, time management, and decision-making strategies.", "display_title": "Time to Reset", "blurb": "Actionable strategies for leadership, focus, and navigating complexity."},
    1367181499: {"topics": [{"node": "gaming", "confidence": 0.9}, {"node": "hobbies", "confidence": 0.65}], "needs_review": False, "rationale": "Actual-play D&D podcast with character-driven storytelling and comedy.", "display_title": "The Damage Guild | A D&D Podcast", "blurb": "D&D campaign combining collaborative storytelling with improv comedy."},
    1367970103: {"topics": [{"node": "sports", "confidence": 0.7}, {"node": "education/how-to", "confidence": 0.65}], "needs_review": True, "rationale": "Team roping athletes discuss careers, mindset, and competitive strategy.", "display_title": "X Factor Roping Podcast", "blurb": "Interviews with elite team ropers on mindset and competitive excellence."},
    1375630453: {"topics": [{"node": "food", "confidence": 0.85}], "needs_review": False, "rationale": "Trader Joe's celebrates its stores, products, and customer stories.", "display_title": "Inside Trader Joe's", "blurb": "Behind-the-scenes look at Trader Joe's culture, products, and community."},
    1377869557: {"topics": [{"node": "music", "confidence": 0.95}], "needs_review": False, "rationale": "Curated electronic dance music radio station hosted by ILLENIUM.", "display_title": "ILLENIUM - Phoenix Radio", "blurb": "Curated EDM radio showcasing ILLENIUM and favorite electronic artists."},
    1380336613: {"topics": [{"node": "news/politics", "confidence": 0.8}, {"node": "economics", "confidence": 0.7}], "needs_review": False, "rationale": "Trade experts analyze tariffs, commerce policy, and global economics.", "display_title": "The Trade Guys", "blurb": "Trade experts break down tariffs, policy, and global commerce impact."},
    1382314891: {"topics": [{"node": "education", "confidence": 0.8}, {"node": "society", "confidence": 0.6}], "needs_review": False, "rationale": "Inclusive education practices, special education, and classroom strategies.", "display_title": "The Inclusion Podcast", "blurb": "Strategies for creating inclusive classrooms for all students."},
    1384700179: {"topics": [{"node": "health/sexuality", "confidence": 0.85}, {"node": "relationships", "confidence": 0.75}], "needs_review": False, "rationale": "Candid lifestyle podcast about swinging, open relationships, and ENM.", "display_title": "Room 77 Swinger Podcast", "blurb": "Candid conversations about swinging, ENM, and non-traditional relationships."},
    1392813061: {"topics": [{"node": "religion/buddhism", "confidence": 0.9}], "needs_review": False, "rationale": "Contemporary Buddhist teachings, mindfulness, and psychology conversations.", "display_title": "The Road Home with Ethan Nichtern", "blurb": "Buddhist teachings and mindfulness conversations with thought leaders."},
    1393739959: {"topics": [{"node": "food", "confidence": 0.9}], "needs_review": False, "rationale": "Smart conversations with food writers, chefs, and cookbook authors.", "display_title": "This Is TASTE", "blurb": "Interviews with leading voices in food writing, cooking, and culture."},
    1393881115: {"topics": [{"node": "sports/tennis", "confidence": 0.95}], "needs_review": False, "rationale": "Tennis players and analysts discuss matches, players, and the sport.", "display_title": "The Rennae Stubbs Tennis Podcast", "blurb": "Tennis commentary and player interviews from Grand Slam perspective."},
    1394669923: {"topics": [{"node": "tv-film/reviews", "confidence": 0.95}], "needs_review": False, "rationale": "Two hosts rate and discuss horror movies with humor.", "display_title": "Horror Movie Club", "blurb": "Casual horror movie reviews with irreverent humor and analysis."},
    1398308821: {"topics": [{"node": "tv-film/reviews", "confidence": 0.95}], "needs_review": False, "rationale": "Horror fan walks newcomer through horror films with commentary.", "display_title": "The Horror Virgin", "blurb": "Horror film journey for newcomers with seasoned fan guidance."},
    1398442165: {"topics": [{"node": "health", "confidence": 0.8}, {"node": "psychology", "confidence": 0.75}], "needs_review": False, "rationale": "Research-backed wellness, health, and personal development guidance.", "display_title": "The Liz Moody Podcast", "blurb": "Wellness conversations with experts on health, anxiety, and productivity."},
    1402378177: {"topics": [{"node": "psychology", "confidence": 0.8}, {"node": "music", "confidence": 0.65}], "needs_review": False, "rationale": "Performance psychology for musicians addressing anxiety and practice.", "display_title": "The Bulletproof Musician", "blurb": "Performance psychology research for musicians beating stage anxiety."},
    1405708885: {"topics": [{"node": "religion/christianity", "confidence": 0.85}], "needs_review": False, "rationale": "Daily Christian devotional with spiritual guidance and encouragement.", "display_title": "LA DOSIS DIARIA ROKA", "blurb": "Daily Christian devotional offering spiritual comfort and encouragement."},
    1409087641: {"topics": [{"node": "personal-journals", "confidence": 0.85}], "needs_review": False, "rationale": "First-person stories about extraordinary personal experiences.", "display_title": "What Was That Like - True Stories. Real People.", "blurb": "Real people share personal stories of survival and extraordinary experiences."},
    1412094313: {"topics": [{"node": "tv-film/history", "confidence": 0.85}], "needs_review": False, "rationale": "Directors discuss films that influenced their careers.", "display_title": "The Movies That Made Me", "blurb": "Directors reflect on films that shaped their creative journeys."},
    1432138159: {"topics": [{"node": "health/sexuality", "confidence": 0.85}, {"node": "relationships", "confidence": 0.75}], "needs_review": False, "rationale": "Candid discussions about intimacy, relationships, and sexuality.", "display_title": "The Love Lab Podcast", "blurb": "Expert conversations on intimacy, sex, and relationship dynamics."},
    1434128185: {"topics": [{"node": "sports", "confidence": 0.8}], "needs_review": False, "rationale": "Breaking Formula 1 news and race analysis from motorsports experts.", "display_title": "The Late Braking F1 Podcast", "blurb": "Breaking F1 news, analysis, and race coverage from motorsports journalists."},
    1434760405: {"topics": [{"node": "tv-film", "confidence": 0.8}, {"node": "culture/pop-culture", "confidence": 0.75}], "needs_review": False, "rationale": "ABC talk show with celebrity guests and pop culture discussion.", "display_title": "The View", "blurb": "Daily talk show with celebrity guests and topical discussion."},
    1434773197: {"topics": [{"node": "tv-film/animation", "confidence": 0.95}], "needs_review": False, "rationale": "Deep-dive analysis of Mobile Suit Gundam anime series.", "display_title": "Mobile Suit Breakdown: the Gundam Podcast", "blurb": "In-depth Gundam anime analysis and discussion."},
    1435363675: {"topics": [{"node": "culture/books", "confidence": 0.9}], "needs_review": False, "rationale": "Book discussion and recommendations from readers.", "display_title": "The Currently Reading Podcast", "blurb": "Book discussion and recommendations for active readers."},
    1435516849: {"topics": [{"node": "history", "confidence": 0.9}], "needs_review": False, "rationale": "Narrative history stories about American political scandals.", "display_title": "American Scandal", "blurb": "Narrative histories of major American political and social scandals."},
    1436651521: {"topics": [{"node": "kids-family/stories", "confidence": 0.9}], "needs_review": False, "rationale": "Twisted retellings of classic fairy tales for dark humor.", "display_title": "Grimm, Grimmer, Grimmest", "blurb": "Dark comedic retellings of classic fairy tales."},
    1437006895: {"topics": [{"node": "music/classical", "confidence": 0.65}, {"node": "music", "confidence": 0.8}], "needs_review": False, "rationale": "Stories behind classic rock songs and artists.", "display_title": "Behind The Song: Classic Rock Chronicles", "blurb": "Origins and stories behind classic rock music and artists."},
    1437213097: {"topics": [{"node": "religion/christianity", "confidence": 0.85}, {"node": "relationships", "confidence": 0.7}], "needs_review": False, "rationale": "Christian marriage advice and relationship guidance for couples.", "display_title": "The Naked Marriage with Dave & Ashley Willis", "blurb": "Christian marriage advice and relationship wisdom for couples."},
    1437682381: {"topics": [{"node": "science", "confidence": 0.9}], "needs_review": False, "rationale": "Josh Clark explores existential scientific topics about human extinction.", "display_title": "The End Of The World with Josh Clark", "blurb": "Science-based exploration of existential threats and scenarios."},
    1437744535: {"topics": [{"node": "science", "confidence": 0.8}], "needs_review": False, "rationale": "Physicians and obstetricians discuss reproductive health and obstetrics.", "display_title": "CREOGs Over Coffee", "blurb": "Reproductive medicine and obstetrics discussions from physicians."},
    1437745759: {"topics": [{"node": "health/sexuality", "confidence": 0.85}, {"node": "relationships", "confidence": 0.75}], "needs_review": False, "rationale": "Lifestyle podcast about the swinger and alternative relationships community.", "display_title": "Front Porch Swingers", "blurb": "Conversations about swinging and alternative relationship lifestyles."},
    1437812269: {"topics": [{"node": "fiction/comedy", "confidence": 0.95}], "needs_review": False, "rationale": "Audio drama following characters navigating death-related situations.", "display_title": "Death by Dying", "blurb": "Comedy audio drama with absurdist humor and character-driven storytelling."},
    1437839593: {"topics": [{"node": "culture/performing-arts", "confidence": 0.8}, {"node": "poetry", "confidence": 0.75}], "needs_review": True, "rationale": "Daily poetry readings with reflection themes.", "display_title": "The Slowdown: Poetry & Reflection Daily", "blurb": "Daily poetry readings for contemplation and reflection."},
    1438044265: {"topics": [{"node": "fiction", "confidence": 0.9}], "needs_review": False, "rationale": "Original short stories and classic fiction narrated.", "display_title": "LitReading - Original Short Stories and Classic Tales", "blurb": "Narrated original short stories and classic fiction."},
    1438566169: {"topics": [{"node": "kids-family/education", "confidence": 0.85}], "needs_review": False, "rationale": "Educational podcast for children with engaging storytelling.", "display_title": "Unspookable", "blurb": "Educational stories for children with engaging presentation."},
    1439091523: {"topics": [{"node": "education", "confidence": 0.65}, {"node": "nature", "confidence": 0.55}], "needs_review": True, "rationale": "Spanish-language horror stories told in live format.", "display_title": "MiedoScope Historias de Miedo en Directo", "blurb": "Live Spanish-language horror storytelling and dramatic narratives."},
    1442743951: {"topics": [{"node": "business/startups", "confidence": 0.8}, {"node": "psychology", "confidence": 0.6}], "needs_review": False, "rationale": "Entrepreneurship motivation and business strategy guidance.", "display_title": "Fuel Your Drive by Josh York", "blurb": "Entrepreneurship and personal motivation for business builders."},
    1443705637: {"topics": [{"node": "paranormal", "confidence": 0.8}], "needs_review": False, "rationale": "Paranormal phenomena, UFOs, and unexplained occurrences discussion.", "display_title": "Believe: Paranormal & UFO Podcast", "blurb": "Paranormal and UFO discussions from a believer's perspective."},
    1444374295: {"topics": [{"node": "religion/christianity", "confidence": 0.85}], "needs_review": False, "rationale": "Christian inspirational content and religious teachings.", "display_title": "The Morning Brew Christian Podcast", "blurb": "Christian teachings and inspirational messages."},
    1444667419: {"topics": [{"node": "craft", "confidence": 0.85}, {"node": "hobbies", "confidence": 0.75}], "needs_review": False, "rationale": "Crafting projects, cooking, reading recommendations combined.", "display_title": "Craft Cook Read Repeat", "blurb": "Creative projects combining craft, cooking, and book recommendations."},
    1445604871: {"topics": [{"node": "comedy", "confidence": 0.85}], "needs_review": False, "rationale": "Stand-up comedian discusses comedy writing and stand-up craft.", "display_title": "The Cover to Cover Podcast with Chris Franjola", "blurb": "Comedy discussions and stand-up craft from established comedians."},
    1447308241: {"topics": [{"node": "education/self-improvement", "confidence": 0.85}], "needs_review": False, "rationale": "Personal finance and wealth-building advice for individuals.", "display_title": "The Rachel Cruze Show", "blurb": "Personal finance guidance and wealth-building strategies."},
    1447749853: {"topics": [{"node": "society/government", "confidence": 0.8}, {"node": "news/politics", "confidence": 0.7}], "needs_review": False, "rationale": "Government procurement, contracts, and policy discussions.", "display_title": "Acquisition Talk", "blurb": "Government procurement and acquisition policy discussions."},
    1448000113: {"topics": [{"node": "religion", "confidence": 0.85}], "needs_review": False, "rationale": "Scholarly discussions of religion from psychological perspective.", "display_title": "Religion on the Mind", "blurb": "Religious studies and psychology of belief systems."},
    1449631195: {"topics": [{"node": "news/daily", "confidence": 0.85}], "needs_review": False, "rationale": "The Economist's daily news roundup and analysis.", "display_title": "The Intelligence from The Economist", "blurb": "Daily news analysis from The Economist."},
    1450018819: {"topics": [{"node": "education/self-improvement", "confidence": 0.9}], "needs_review": False, "rationale": "Quick-tip daily podcast about productivity and personal growth.", "display_title": "Before Breakfast", "blurb": "Daily productivity and personal development tips."},
    1450540825: {"topics": [{"node": "science", "confidence": 0.85}], "needs_review": False, "rationale": "Explorations of interconnected ideas across science and philosophy.", "display_title": "Manifold", "blurb": "Interdisciplinary science and philosophy conversations."},
    1451120629: {"topics": [{"node": "business/startups", "confidence": 0.8}, {"node": "psychology", "confidence": 0.65}], "needs_review": False, "rationale": "Entrepreneurship accountability and business growth strategies.", "display_title": "The Daily Mastermind", "blurb": "Daily entrepreneurship and business growth guidance."},
    1451462443: {"topics": [{"node": "health/yoga", "confidence": 0.65}, {"node": "personal-journals", "confidence": 0.7}], "needs_review": True, "rationale": "Yoga and personal practice guidance from instructor Elena Brower.", "display_title": "Practice You with Elena Brower", "blurb": "Yoga and personal practice guidance from instructor Elena Brower."},
}

for show in batch['shows']:
    apple_id = show['apple_collection_id']
    if apple_id in classifications:
        results['results'][str(apple_id)] = {
            **classifications[apple_id],
            "model": "claude-code-cron (tier 1)"
        }

# Write results
with open('data-local/classify-results-fresh-2026-07-25-49fbedf1.json', 'w') as f:
    json.dump(results, f, indent=2)

print(f"Classified {len(results['results'])} shows")
