import fs from 'fs';

const batch = JSON.parse(fs.readFileSync('/home/user/foray/data-local/classify-batch-fresh-2026-08-06-e68d8e5f.json', 'utf8'));

const results = {
  batch_id: batch.batch_id,
  results: {}
};

const classifications = [
  { id: 1584566207, topics: [{ node: 'culture/design', confidence: 0.3 }], needs_review: true, rationale: 'Minimal description and episode data; unclear focus.', display_title: 'EPF', blurb: 'Insufficient information to classify.' },
  { id: 1591962689, topics: [{ node: 'news/commentary', confidence: 0.9 }], needs_review: false, rationale: 'Judge Napolitano interviews experts on foreign policy, war, and constitutional issues.', display_title: 'Judging Freedom', blurb: 'Legal analysis and interviews on US foreign policy, civil liberties, and constitutional matters.' },
  { id: 1592165387, topics: [{ node: 'religion/christianity', confidence: 0.95 }], needs_review: false, rationale: 'Daily biblical study and application from Genesis through full Bible; explicitly Christian.', display_title: 'A Year in the Bible with Daily Grace', blurb: 'Daily Bible study journey connecting scripture to Jesus, with spiritual reflection.' },
  { id: 1592182331, topics: [{ node: 'music', confidence: 0.85 }, { node: 'culture', confidence: 0.4 }], needs_review: false, rationale: 'Deep-dive discography reviews with artists rating their own work and others.', display_title: 'Discograffiti', blurb: 'Artist interviews and track-by-track album reviews from music obsessives.' },
  { id: 1592443967, topics: [{ node: 'comedy/stand-up', confidence: 0.85 }], needs_review: false, rationale: 'Hebrew-language comedy podcast with stand-up comedians and entertainment guests.', display_title: 'נכנסים לפינות עם רז ספני ומתן פרץ', blurb: 'Hebrew comedy talks with entertainment figures and pop culture discussion.' },
  { id: 1592508833, topics: [{ node: 'culture/pop-culture', confidence: 0.8 }, { node: 'tv-film/reviews', confidence: 0.5 }], needs_review: false, rationale: 'Reality TV news, Bachelorette recaps, and celebrity pop culture commentary.', display_title: 'She\'s All Bach', blurb: 'Reality TV and pop culture news with Bachelorette franchise recaps and updates.' },
  { id: 1592765405, topics: [{ node: 'religion/spirituality', confidence: 0.85 }], needs_review: false, rationale: 'ACA 12-step recovery program speakers sharing experiences with addiction and dysfunction.', display_title: 'ACA Adult Children Voices Across America Speaker Meeting', blurb: 'Recovery stories from people using 12-step program for adult children of dysfunctional families.' },
  { id: 1592841545, topics: [{ node: 'health', confidence: 0.85 }, { node: 'education', confidence: 0.4 }], needs_review: false, rationale: 'Hospice nursing focus: burnout prevention, patient care, end-of-life guidance.', display_title: 'The Hospice Nursing Podcast', blurb: 'Hospice care insights, burnout prevention, and end-of-life patient support strategies.' },
  { id: 1593296999, topics: [{ node: 'craft/woodworking', confidence: 0.9 }], needs_review: false, rationale: 'UK woodworking makers discuss tools, techniques, and workshop projects in casual conversations.', display_title: 'Workshop Banter', blurb: 'Woodworking discussions, tool reviews, and maker workshop projects.' },
  { id: 1593424985, topics: [{ node: 'business/startups', confidence: 0.9 }, { node: 'education', confidence: 0.4 }], needs_review: false, rationale: 'Startup ideas, AI marketing agents, AI tools for entrepreneurs and business builders.', display_title: 'The Startup Ideas Podcast', blurb: 'Weekly startup ideas and AI-powered business strategy from startup founder Greg Isenberg.' },
  { id: 1594016117, topics: [{ node: 'nature/earth-science', confidence: 0.85 }, { node: 'society', confidence: 0.4 }], needs_review: false, rationale: 'Environmental sustainability, climate change, conservation, biodiversity with leading experts.', display_title: 'Sustainability, Climate Change, Renewable Energy, Politics, Activism, Biodiversity, Carbon Footprint, Wildlife, Regenerative', blurb: 'Environmental sustainability and climate action from conservation leaders and experts.' },
  { id: 1594463441, topics: [{ node: 'food', confidence: 0.8 }, { node: 'business', confidence: 0.5 }], needs_review: false, rationale: 'Restaurant industry conversations with chefs and owners on hospitality, change, and survival.', display_title: 'Niver Niver Land', blurb: 'Restaurant industry conversations from award-winning restaurateur Tim Niver.' },
  { id: 1594606997, topics: [{ node: 'adventure/exploration', confidence: 0.8 }, { node: 'sports', confidence: 0.4 }], needs_review: false, rationale: 'BASE jumping culture, safety, legal/ethical issues, and athlete interviews.', display_title: 'Exit Point', blurb: 'BASE jumping culture, safety, and extreme sports interviews and analysis.' },
  { id: 1596600575, topics: [{ node: 'culture/fashion', confidence: 0.75 }, { node: 'business/careers', confidence: 0.4 }], needs_review: false, rationale: 'Hair extension education, business strategy, and stylist career development.', display_title: 'Flipping The Industry', blurb: 'Hair extension education and beauty industry business strategy from IBE founder.' },
  { id: 1596647855, topics: [{ node: 'business/careers', confidence: 0.9 }, { node: 'education', confidence: 0.5 }], needs_review: false, rationale: 'Job interview tips, career advice, and hiring strategies from tech company veteran.', display_title: 'Girl, You\'re Hired: Job Interview Tips Podcast', blurb: 'Job interview tips and career advice from tech industry recruiter Lena Sernoff.' },
  { id: 1596795035, topics: [{ node: 'news/commentary', confidence: 0.85 }, { node: 'news/politics', confidence: 0.5 }], needs_review: false, rationale: 'Political news commentary for center audience; Monday-Thursday episodes on current events.', display_title: 'unDivided with Brandi Kruse', blurb: 'Balanced political and cultural commentary with host Brandi Kruse.' },
  { id: 1597127405, topics: [{ node: 'nature/pets', confidence: 0.9 }], needs_review: false, rationale: 'Educational dog breed profiles with behavioral traits, history, and trivia from TV series.', display_title: 'Dogs 101', blurb: 'Educational guide to dog breeds with behavioral traits, history, and famous examples.' },
  { id: 1597212401, topics: [{ node: 'business/startups', confidence: 0.8 }, { node: 'business/founders', confidence: 0.8 }], needs_review: false, rationale: 'Entrepreneur and CEO interviews exploring business lessons from great companies.', display_title: 'ACQ2 by Acquired', blurb: 'Deep-dive conversations with founders and CEOs about business strategy and leadership.' },
  { id: 1599190589, topics: [{ node: 'tv-film/after-shows', confidence: 0.9 }], needs_review: false, rationale: 'HBO Max Station Eleven companion podcast with cast/crew interviews and episode analysis.', display_title: 'Station Eleven: The Podcast', blurb: 'Behind-the-scenes companion podcast for HBO Max\'s Station Eleven miniseries.' },
  { id: 1599316865, topics: [{ node: 'business/marketing', confidence: 0.85 }, { node: 'business/careers', confidence: 0.4 }], needs_review: false, rationale: 'Private practice growth strategies for dental and medical professionals.', display_title: 'Private Practice Playbook', blurb: 'Private practice growth strategy from Jay Geier for dentists and health practitioners.' },
  { id: 1599573815, topics: [{ node: 'automotive', confidence: 0.85 }, { node: 'sports/endurance', confidence: 0.3 }], needs_review: false, rationale: 'Porsche-only podcast with news, club information, and restoration stories.', display_title: 'Porsche Club Insider', blurb: 'Porsche news and culture from the Porsche Club of America.' },
  { id: 1600568435, topics: [{ node: 'sports/golf', confidence: 0.9 }], needs_review: false, rationale: 'Golf coaching, game improvement, instruction, and current golf industry news.', display_title: 'The Skillest Podcast', blurb: 'Golf coaching and instruction from two of the game\'s top coaches.' },
  { id: 1601135051, topics: [{ node: 'news/tech', confidence: 0.85 }, { node: 'computing', confidence: 0.4 }], needs_review: false, rationale: 'Weekly streaming media and infrastructure news with data-driven analysis.', display_title: 'The Dan Rayburn Podcast', blurb: 'Streaming media industry news and analysis without hype.' },
  { id: 1601611493, topics: [{ node: 'kids-family/parenting', confidence: 0.9 }, { node: 'education/self-improvement', confidence: 0.4 }], needs_review: false, rationale: 'Science-backed parenting advice for teens; expert interviews on adolescent development.', display_title: 'Parenting Teenagers Untangled', blurb: 'Science-backed parenting advice for tweens and teens with expert interviews.' },
  { id: 1602287945, topics: [{ node: 'music/classical', confidence: 0.85 }, { node: 'culture', confidence: 0.4 }], needs_review: false, rationale: 'Song-by-song musical analysis of Hamilton on Disney Plus.', display_title: 'Hamilton Shot By Shot', blurb: 'Song-by-song analysis of the hit musical Hamilton.' },
  { id: 1602310595, topics: [{ node: 'tv-film/animation', confidence: 0.8 }, { node: 'culture/pop-culture', confidence: 0.4 }], needs_review: false, rationale: 'Comic book analysis covering entire Spider-Man publication history and related titles.', display_title: 'Amazing Spider-Man Classics', blurb: 'Comic book deep-dives covering Spider-Man stories with guest experts.' },
  { id: 1602556715, topics: [{ node: 'religion/islam', confidence: 0.85 }], needs_review: false, rationale: 'Islamic scholarly commentary on Nahj Al-Balaghah sermons by Imam Ali.', display_title: 'A Commentary on Nahj Al-Balaghah - Mizan Institute', blurb: 'Islamic scholarly analysis of Imam Ali\'s sermons and teachings.' },
  { id: 1603002149, topics: [{ node: 'tv-film/history', confidence: 0.85 }, { node: 'history', confidence: 0.5 }], needs_review: false, rationale: 'Minute-by-minute detailed analysis of the film Jaws with expert commentary.', display_title: 'The Jaws Obsession', blurb: 'Minute-by-minute deep analysis of the film Jaws with expanded universe lore.' },
  { id: 1603654907, topics: [{ node: 'fiction/comedy', confidence: 0.85 }, { node: 'fiction', confidence: 0.5 }], needs_review: false, rationale: 'Comedy fiction podcast about mysterious mansion with supernatural characters and mystery elements.', display_title: 'Ghosthoney\'s Dream Machine', blurb: 'Comedic fiction podcast about mysterious mansion with supernatural characters.' },
  { id: 1603857827, topics: [{ node: 'business/startups', confidence: 0.8 }, { node: 'business/founders', confidence: 0.7 }], needs_review: false, rationale: 'Entrepreneurial nurse practitioners sharing stories of practice ownership and building.', display_title: 'The Elite Nurse Practitioner Show', blurb: 'Business advice for nurse practitioners starting and scaling their practices.' },
  { id: 1603857929, topics: [{ node: 'kids-family/education', confidence: 0.9 }], needs_review: false, rationale: 'Daily kids science and curiosity questions answered by experts in fun format.', display_title: 'Moment Of Um', blurb: 'Daily science questions answered for kids by experts in fun format.' },
  { id: 1604560433, topics: [{ node: 'sports/golf', confidence: 0.85 }, { node: 'psychology', confidence: 0.4 }], needs_review: false, rationale: 'Golf coaching focused on mental game, peak performance, and flow state.', display_title: 'Flow Golf Podcast with Rick Sessinghaus & Hallam Morgan', blurb: 'Golf coaching on mental game, peak performance, and flow state.' },
  { id: 1604634359, topics: [{ node: 'news/daily', confidence: 0.9 }], needs_review: false, rationale: 'Daily morning news show with breaking news, interviews, and entertainment from ABC.', display_title: 'Good Morning America', blurb: 'America\'s morning news show with breaking news and interviews.' },
  { id: 1604892683, topics: [{ node: 'culture/design', confidence: 0.85 }, { node: 'education/how-to', confidence: 0.4 }], needs_review: false, rationale: 'Interior design and home renovation advice for renters and homeowners on budget.', display_title: 'So, How Do You… The Interiors Podcast', blurb: 'Interior design tips and home renovation guidance for any budget.' },
  { id: 1605281717, topics: [{ node: 'sports/football', confidence: 0.9 }], needs_review: false, rationale: 'NFL Draft analysis with mock drafts, scouting reports, and player rankings.', display_title: 'NFL Stock Exchange: An NFL Draft Podcast', blurb: 'NFL Draft analysis with mock drafts and player scouting.' },
  { id: 1605386171, topics: [{ node: 'health/mental', confidence: 0.85 }, { node: 'psychology', confidence: 0.5 }], needs_review: false, rationale: 'ADHD support and wellness podcast for women with expert interviews and guidance.', display_title: 'ADHD Women\'s Wellbeing Podcast', blurb: 'ADHD support and wellness for women with expert interviews.' },
  { id: 1605654449, topics: [{ node: 'tv-film/history', confidence: 0.85 }, { node: 'history', confidence: 0.4 }], needs_review: false, rationale: 'Hollywood history from Golden Age with interviews from legends in film, TV, and music.', display_title: 'Calling Old Hollywood', blurb: 'Hollywood history with interviews from Golden Age entertainment legends.' },
  { id: 1605865991, topics: [{ node: 'relationships', confidence: 0.9 }, { node: 'psychology', confidence: 0.5 }], needs_review: false, rationale: 'Emotional abuse, coercive control, and narcissistic relationships coaching and guidance.', display_title: 'You Are Not Crazy', blurb: 'Guidance on emotional abuse, coercive control, and narcissistic relationships.' },
  { id: 1606051811, topics: [{ node: 'fiction/drama', confidence: 0.85 }], needs_review: false, rationale: 'Horror fiction anthology with narrated stories and atmospheric music.', display_title: 'Fear From the Heartland — A Horror Fiction Anthology and Scary Stories Podcast', blurb: 'Horror fiction anthology with professional narration and music.' },
  { id: 1606449047, topics: [{ node: 'news', confidence: 0.75 }, { node: 'business', confidence: 0.6 }], needs_review: false, rationale: 'Daily irreverent business and tech news with startup and entrepreneurship focus.', display_title: 'The Hustle Daily Show', blurb: 'Daily business and tech news with entrepreneurship focus and startup insights.' },
  { id: 1606834013, topics: [{ node: 'news/politics', confidence: 0.85 }], needs_review: false, rationale: 'Conservative political commentary and interviews from Newsweek senior editor.', display_title: 'The Josh Hammer Show', blurb: 'Conservative political and cultural commentary with expert interviews.' },
  { id: 1606887551, topics: [{ node: 'science/chemistry', confidence: 0.5 }, { node: 'medicine', confidence: 0.5 }], needs_review: true, rationale: 'Veterinary medicine and disease management; not chemistry-focused despite title mention.', display_title: 'Bova UK Podcast', blurb: 'Veterinary medicine discussions on diagnosis, treatment, and disease management.' },
  { id: 1607177435, topics: [{ node: 'science/chemistry', confidence: 0.8 }, { node: 'history', confidence: 0.4 }], needs_review: false, rationale: 'Chemistry history, notable scientists, and everyday chemistry applications.', display_title: 'Cowboy Chemistry', blurb: 'Chemistry history, notable scientists, and chemistry in everyday life.' },
  { id: 1607184755, topics: [{ node: 'business/management', confidence: 0.85 }, { node: 'business/founders', confidence: 0.4 }], needs_review: false, rationale: 'Retail leadership and business interviews from Nordstrom president Pete Nordstrom.', display_title: 'The Nordy Pod', blurb: 'Business and leadership insights from Nordstrom\'s fourth-generation leadership.' }
];

// Process all shows
batch.shows.forEach(show => {
  const classification = classifications.find(c => c.id === show.apple_collection_id);
  if (classification) {
    results.results[show.apple_collection_id] = {
      topics: classification.topics,
      needs_review: classification.needs_review,
      rationale: classification.rationale,
      display_title: classification.display_title,
      blurb: classification.blurb,
      model: 'claude-code-cron (tier 1)'
    };
  }
});

fs.writeFileSync(
  '/home/user/foray/data-local/classify-results-fresh-2026-08-06-e68d8e5f.json',
  JSON.stringify(results, null, 2)
);

console.log(`Classified ${Object.keys(results.results).length} shows`);
