#!/usr/bin/env node
/* Wire `mobile/gradle/foray-signing.gradle` into a GENERATED Android project.
 *
 * WHY A SCRIPT AND NOT A COMMITTED build.gradle
 * `mobile/android/` is regenerated by `cap add android` on every machine and
 * every CI run (`mobile/.gitignore`), so `app/build.gradle` is Capacitor
 * template output with no signing config and a hardcoded `versionCode 1`. The
 * decision has to live in a tracked file and be re-applied after generation —
 * exactly the shape `foray-audio` already uses, where `cap sync` re-derives the
 * plugin's include lines from `mobile/package.json` every time.
 *
 * WHAT IT DOES, IN FULL
 *   1. copies the tracked `foray-signing.gradle` to `<android>/foray-signing.gradle`
 *   2. appends ONE line to `<android>/app/build.gradle`:
 *        apply from: "$rootDir/foray-signing.gradle"
 *   3. re-reads both from disk and asserts the result, because a write that
 *      reports success and a file that contains the line are different claims
 *      (this repo has paid for the difference more than once).
 *
 * THE APPEND IS AT THE END OF THE FILE ON PURPOSE. Gradle's `android { }` is a
 * re-openable extension block, so a second `android { }` in an applied script
 * configures the same object; and `apply from:` runs during CONFIGURATION, before
 * AGP creates the variants in its `afterEvaluate`, so a signing config added this
 * late is still in time to be attached to the release build type.
 *
 * IDEMPOTENT. `cap sync` may run more than once in a job, and a second copy of
 * the apply line would be a second `signingConfigs { forayRelease { … } }` —
 * harmless today and not something to rely on. Re-running is a no-op that still
 * verifies.
 *
 * IT REFUSES TO TOUCH ANYTHING THAT IS NOT A GENERATED PROJECT, the same guard
 * `tools/mobile/probe/install-probe.mjs` carries and for the same reason: the
 * argument for a script that edits build files is that it only ever edits build
 * OUTPUT.
 *
 * USAGE
 *   node tools/mobile/wire-signing.mjs mobile/android
 *   node tools/mobile/wire-signing.mjs mobile/android --check   (verify only)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(HERE, "..", "..");

/** The tracked source of truth. */
export const SIGNING_GRADLE_SOURCE = path.join(REPO_ROOT, "mobile", "gradle", "foray-signing.gradle");

/** The basename it is copied to, inside the generated project's root. */
export const SIGNING_GRADLE_NAME = "foray-signing.gradle";

/** The exact line appended to `app/build.gradle`.
 *
 *  `$rootDir` is Gradle's own property for the ROOT project directory —
 *  `mobile/android` — evaluated by Groovy, not by this script, which is why the
 *  string is single-quoted here and double-quoted there. A relative `'../foray-signing.gradle'`
 *  would also work today and would break the day someone applies this from a
 *  module at a different depth. */
export const APPLY_LINE = 'apply from: "$rootDir/foray-signing.gradle"';

/** The four files a directory must have before we will call it a generated
 *  Capacitor Android project and start writing into it.
 *
 *  `capacitor.settings.gradle` is in the list because it is the one file NO
 *  hand-made directory has: `cap sync` writes it, and `android-build.yml`'s
 *  highest-value assertion reads it. A directory carrying all four is build
 *  output, not a checkout. */
export const GENERATED_MARKERS = [
  "app/build.gradle",
  "settings.gradle",
  "capacitor.settings.gradle",
  "gradlew",
];

export class WireSigningError extends Error {}

/** Decide whether `dir` is a generated Capacitor Android project.
 *
 *  Returns the list of MISSING markers — empty means yes. Returned rather than
 *  thrown so the caller can name all of them at once; a script that reports one
 *  missing file per run is three runs to learn what is wrong. */
export function missingMarkers(dir, exists = (p) => fs.existsSync(p)) {
  return GENERATED_MARKERS.filter((m) => !exists(path.join(dir, m)));
}

/** Is the apply line already in this `app/build.gradle` text?
 *
 *  COMMENT-BLIND ON PURPOSE, and this is the assertion that would otherwise go
 *  vacuous. `foray-signing.gradle` is discussed by name in comments in several
 *  files, so a substring test for `foray-signing.gradle` would report "already
 *  wired" against a build.gradle that merely mentions it. The test is for the
 *  whole apply statement on a line that is not commented out. */
export function hasApplyLine(text) {
  return text
    .split(/\r?\n/)
    .some((line) => line.trim() === APPLY_LINE);
}

/** The text `app/build.gradle` should have after wiring. Pure, so the test can
 *  assert the transform without a filesystem. */
export function withApplyLine(text) {
  if (hasApplyLine(text)) return text;
  const body = text.endsWith("\n") ? text : text + "\n";
  return (
    body +
    "\n" +
    "// Added by tools/mobile/wire-signing.mjs. Release signing and version\n" +
    "// stamping live in the tracked mobile/gradle/foray-signing.gradle, because\n" +
    "// this file is Capacitor template output and is overwritten by `cap add`.\n" +
    APPLY_LINE +
    "\n"
  );
}

/** Wire the signing include into the generated project at `androidDir`.
 *
 *  @param {string} androidDir  the generated project root, e.g. `mobile/android`
 *  @param {{check?: boolean}} opts  `check` verifies without writing
 *  @returns {{applied: boolean, alreadyWired: boolean, gradleFile: string}}
 */
export function wireSigning(androidDir, opts = {}) {
  const missing = missingMarkers(androidDir);
  if (missing.length > 0) {
    throw new WireSigningError(
      `${androidDir} is not a generated Capacitor Android project — missing: ${missing.join(", ")}. ` +
        `Run \`npm run add:android\` in mobile/ first; this script only ever edits build output.`
    );
  }
  if (!fs.existsSync(SIGNING_GRADLE_SOURCE)) {
    throw new WireSigningError(`the tracked signing include is missing: ${SIGNING_GRADLE_SOURCE}`);
  }

  const appGradlePath = path.join(androidDir, "app", "build.gradle");
  const before = fs.readFileSync(appGradlePath, "utf8");
  const alreadyWired = hasApplyLine(before);

  if (opts.check) {
    const copied = fs.existsSync(path.join(androidDir, SIGNING_GRADLE_NAME));
    if (!alreadyWired || !copied) {
      throw new WireSigningError(
        `not wired: apply line ${alreadyWired ? "present" : "MISSING"}, ` +
          `${SIGNING_GRADLE_NAME} ${copied ? "present" : "MISSING"}`
      );
    }
    return { applied: false, alreadyWired: true, gradleFile: appGradlePath };
  }

  fs.copyFileSync(SIGNING_GRADLE_SOURCE, path.join(androidDir, SIGNING_GRADLE_NAME));
  if (!alreadyWired) fs.writeFileSync(appGradlePath, withApplyLine(before), "utf8");

  /* RE-READ FROM DISK. The point is not paranoia about fs.writeFileSync; it is
     that `alreadyWired` was computed from a string and everything downstream
     depends on the FILE. A copy onto a read-only path, or a write into a
     different directory than the one Gradle will read, both look like success
     from here otherwise. */
  const after = fs.readFileSync(appGradlePath, "utf8");
  if (!hasApplyLine(after)) {
    throw new WireSigningError(`wrote ${appGradlePath} but the apply line is not in it — signing would be silently off`);
  }
  const copiedPath = path.join(androidDir, SIGNING_GRADLE_NAME);
  if (!fs.existsSync(copiedPath)) {
    throw new WireSigningError(`copied nothing to ${copiedPath} — the apply line would fail the build`);
  }

  return { applied: !alreadyWired, alreadyWired, gradleFile: appGradlePath };
}

/* ─────────────────────────────── CLI ─────────────────────────────────────── */

function main(argv) {
  const args = argv.filter((a) => a !== "--check");
  const check = argv.includes("--check");
  const target = args[0];
  if (!target) {
    console.error("usage: node tools/mobile/wire-signing.mjs <generated android dir> [--check]");
    return 2;
  }
  try {
    const r = wireSigning(path.resolve(target), { check });
    if (check) console.log(`signing include is wired into ${r.gradleFile}`);
    else if (r.applied) console.log(`wired ${SIGNING_GRADLE_NAME} into ${r.gradleFile}`);
    else console.log(`${r.gradleFile} was already wired; refreshed ${SIGNING_GRADLE_NAME}`);
    return 0;
  } catch (err) {
    console.error(err instanceof WireSigningError ? err.message : err);
    return 1;
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  process.exit(main(process.argv.slice(2)));
}
