/* The Google Play listing assets, guarded.
 *
 * WHAT THIS IS FOR
 * `docs/store/play/` is a submission package: a founder opens the Play Console
 * and pastes out of it. Every failure mode here is silent at the point it is
 * introduced and loud only when the Console rejects the upload — or, worse, when
 * it accepts something wrong. So the properties Play itself enforces are
 * enforced here first, where a diff can show them.
 *
 * THE TWO HALVES ARE GUARDED DIFFERENTLY, AND THE DIFFERENCE IS HONEST.
 *
 *   The feature graphic is GENERATED, and tests 1-3 are the same guard
 *   `tools/brand/build-icons.test.mjs` puts on the icons: decode the committed
 *   file, re-render from `tools/brand/4a-logo.png` in memory, compare pixels.
 *   Hand-edit the banner and the build goes red. Pixels and not bytes for the
 *   reason that suite's header gives at length -- zlib output is not stable
 *   across versions, so a byte compare fails on CI's Node against a developer's
 *   for a reason that has nothing to do with the image.
 *
 *   The screenshots are CAPTURED from the deployed app and cannot be
 *   regenerated by a test: the pipeline needs a browser. Claiming otherwise
 *   would be the "green test that pins nothing" this repo has found five times.
 *   What IS pinned is everything Play checks -- exact pixel size, aspect,
 *   format, count, byte ceiling -- plus the existence of the recipe that
 *   produced them (CAPTURE.md), because a screenshot nobody can reproduce is a
 *   stale artefact the moment the UI moves. Test 9 is the one that matters
 *   there: it fails if the screenshots are still committed and the recipe is
 *   gone.
 *
 * MUTATIONS RUN AND KILLED. Each names the test that kills it, and where a
 * mutation is killed by a DIFFERENT test than the obvious one, that is recorded
 * rather than smoothed over. THE FIRST TWO ARE THE INTERESTING ONES: an earlier
 * version of this header claimed them for the pixel test, review ran them, and
 * they were GREEN. They are killed now because a test was added, not because the
 * claim was reworded.
 *
 *   - flip one byte in feature-graphic.png            -> "what the master renders to"
 *   - regenerate with SPAN_W = 0.50, leaving it 0.50  -> "composition constants
 *       are pinned". NOT the pixel test, and this is the trap this whole suite is
 *       arranged around: that test re-renders through the same generator, so
 *       moving a constant moves the committed file and the fresh render TOGETHER
 *       and they still agree at the new size. The banner came out 22% smaller
 *       (dw 655 -> 512) with all twelve tests green. What the pixel test actually
 *       catches is a STALE artefact — mutate the constant, regenerate, put the
 *       constant back, and it fires. That is a real and different guard, and it
 *       is not this one.
 *   - regenerate with SNAP = 30, leaving it 30         -> "composition constants
 *       are pinned", for exactly the same reason. SNAP is imported from
 *       build-icons.mjs, so this also fires if the icons' threshold moves.
 *       Both of these also fire "stated character counts and byte size", because
 *       a requantised banner is a different number of bytes and README.md still
 *       claims the old one. Two independent tests, which is the right number for
 *       a mutation that survived a whole review round.
 *   - encode({rgb:false}) so the banner carries alpha -> "1024x500, 8-bit, no alpha".
 *       NOT the pixel test: decode() normalises both sides to RGBA, so an opaque
 *       alpha channel compares equal. Colour type is the only thing that sees it.
 *   - render the banner at 1024x512                   -> "1024x500, 8-bit, no alpha".
 *       Again NOT the pixel test, same both-sides-move reason as SPAN_W. Only
 *       Play's literal numbers catch it, which is why they are written out as
 *       constants and asserted against the generator's exports rather than
 *       derived from them.
 *   - resize one screenshot to 700x1280               -> "exactly 720x1280"
 *   - resize one screenshot to 360x640                -> "exactly 720x1280". Still
 *       exactly 9:16 and still legal for Play, so a ratio-only check passes it
 *       and the listing silently loses half its resolution.
 *   - delete one screenshot, leaving three            -> "README names every asset"
 *   - delete two, leaving two                         -> "README names every asset".
 *       The count test does NOT fire, correctly: two is Play's floor.
 *   - delete three and update README + CAPTURE too    -> "enough phone screenshots".
 *       The split matters: the README test catches an inconsistent package, the
 *       count test catches a consistent one that Play would reject.
 *   - an 81-character short description               -> "fits Play's 80-character field"
 *   - a 4001-character full description               -> "fits Play's 4000-character field"
 *   - add "Trusted by thousands of listeners."        -> "a claim we cannot stand behind"
 *   - add "Built by a small indie team."              -> "signals the size of the company"
 *   - remove the "published by JW Labs LLC" line      -> "names the publisher"
 *   - drop feature-graphic.png from README.md         -> "README names every asset"
 *   - delete CAPTURE.md                               -> "capture recipe is committed"
 *   - write "9999 characters" in README.md            -> "stated character counts
 *       are the real ones". This one was also green before review: the README's
 *       three numbers, which are the only thing telling the founder they pasted a
 *       whole field, were guarded by nothing, and had already drifted by 2.
 *
 * ONE MUTATION IS DELIBERATELY NOT COVERED. Nothing here can tell a screenshot
 * of the real app from a screenshot of a mock-up, or from a screenshot of a
 * version of the app that no longer exists. That is not a gap a test can close
 * -- it is why CAPTURE.md records the exact procedure rather than a description
 * of one, and why the screenshots are dated in it.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { decode } from "../brand/png.mjs";
import { loadMaster } from "../brand/build-icons.mjs";
import { renderFeatureGraphic, WIDTH, HEIGHT, SPAN_W, SPAN_H, SNAP, OUTPUT } from "./build-feature-graphic.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const DIR = "docs/store/play";
const read = (rel) => fs.readFileSync(path.join(ROOT, rel));
const text = (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8");

/* Play's own limits, as of the 2026 Console. Named rather than inlined so a
   reader can check them against the help page without reading five assertions. */
const PLAY = {
  FEATURE_W: 1024,
  FEATURE_H: 500,
  SHORT_MAX: 80,
  FULL_MAX: 4000,
  MIN_SHOTS: 2,          // Play refuses to publish with fewer
  MAX_SHOTS: 8,          // Play refuses to accept more
  SHOT_MIN_SIDE: 320,
  SHOT_MAX_SIDE: 3840,
  SHOT_MAX_BYTES: 8 * 1024 * 1024,
};

/* The one size every phone screenshot in this package is cut to. 720x1280 is
   exactly 9:16 and a real Android phone resolution; see CAPTURE.md for why the
   capture is resampled to it rather than shipped at its native crop. */
const SHOT_W = 720, SHOT_H = 1280;

/* IHDR is at a fixed offset in every PNG: 8 signature bytes, then a 4-byte
   length and the 4-byte type, so the fields start at 16. */
function pngHeader(buf) {
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20), depth: buf[24], colour: buf[25] };
}

/* JPEG has no fixed-offset header -- the dimensions live in whichever SOFn
   segment the encoder emitted, after an arbitrary run of APPn/DQT/COM segments.
   Walking to it is ~15 lines and means this suite can measure the screenshots
   without the repo growing an image dependency to read four numbers.

   The standalone markers -- no length field, advance by two -- are TEM (01),
   RST0-RST7 (D0-D7), SOI (D8) and EOI (D9), per ITU T.81 B.1.1.3. Everything
   else carries a 16-bit length that includes its own two bytes.

   C4 (Huffman tables), C8 (JPEG extension) and CC (arithmetic conditioning)
   share the C0-CF range with the SOFn markers but are NOT frame headers, which
   is the easy bug here: include them and this returns two bytes of a Huffman
   table as the image height. In today's four files DHT happens to follow SOF0,
   so the exclusion is not exercised by the committed data -- it was verified
   against synthetic streams that place each of the three BEFORE the frame
   header. */
const SOF = new Set([0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf]);
const STANDALONE = new Set([0x01, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9]);
function jpegHeader(buf) {
  if (buf[0] !== 0xff || buf[1] !== 0xd8) throw new Error("not a JPEG");
  let p = 2;
  while (p + 3 < buf.length) {
    if (buf[p] !== 0xff) throw new Error("lost JPEG marker alignment");
    const marker = buf[p + 1];
    /* Fill bytes: any number of FFs may precede a marker (T.81 B.1.1.2). */
    if (marker === 0xff) { p += 1; continue; }
    if (STANDALONE.has(marker)) { p += 2; continue; }
    const len = buf.readUInt16BE(p + 2);
    if (SOF.has(marker)) {
      /* Bounds-checked so a truncated frame header says so, rather than
         surfacing as a bare ERR_OUT_OF_RANGE from readUInt16BE. */
      if (p + 9 > buf.length) throw new Error("truncated SOF segment");
      return { height: buf.readUInt16BE(p + 5), width: buf.readUInt16BE(p + 7) };
    }
    p += 2 + len;
  }
  throw new Error("no SOF segment: not a baseline or progressive JPEG");
}

function imageSize(rel) {
  const buf = read(rel);
  if (rel.endsWith(".png")) { const h = pngHeader(buf); return { ...h, bytes: buf.length }; }
  return { ...jpegHeader(buf), bytes: buf.length };
}

/** Every phone screenshot in the package, in the order they are numbered.
    Lexicographic sort, which would put `screenshot-10-` before `screenshot-2-`;
    safe only because MAX_SHOTS is 8, so a tenth cannot exist. The order is what
    the README's upload table depends on, so if Play ever raises that ceiling,
    sort numerically here. The pattern matches the one in the README-coverage
    test below; keep them in step. */
function screenshots() {
  return fs.readdirSync(path.join(ROOT, DIR))
    .filter((f) => /^screenshot-\d+-[\w-]+\.(?:jpg|png)$/.test(f))
    .sort();
}

/* ---------- the feature graphic: generated, so pinned to the master ---------- */

test("feature-graphic.png is exactly what the brand master renders to", () => {
  const committed = decode(read(OUTPUT));
  const fresh = decode(renderFeatureGraphic(loadMaster()));
  assert.equal(committed.width, fresh.width, "width");
  assert.equal(committed.height, fresh.height, "height");
  assert.ok(
    committed.data.equals(fresh.data),
    `${OUTPUT} pixels differ from a fresh render of tools/brand/4a-logo.png. ` +
      `Do not edit it by hand: change the master and run ` +
      `node tools/store/build-feature-graphic.mjs.`
  );
});

test("feature-graphic.png is exactly 1024x500, 8-bit, and carries no alpha", () => {
  const h = pngHeader(read(OUTPUT));
  /* Not "about" 1024x500. The Console rejects every other size outright, which
     is the single most likely way this submission bounces. */
  assert.equal(h.width, PLAY.FEATURE_W, "feature graphic width");
  assert.equal(h.height, PLAY.FEATURE_H, "feature graphic height");
  assert.equal(WIDTH, PLAY.FEATURE_W, "the generator's WIDTH must be Play's");
  assert.equal(HEIGHT, PLAY.FEATURE_H, "the generator's HEIGHT must be Play's");
  assert.equal(h.depth, 8, "bit depth");
  assert.equal(h.colour, 2, "must be RGB (colour type 2), not RGBA");
});

test("the banner's composition constants are pinned, not merely used", () => {
  /* THE HOLE THIS CLOSES, found in review and worth stating plainly because the
     suite above it looks like it already covers this. "Regenerate with
     SPAN_W = 0.50" leaves the whole suite GREEN: the pixel test re-renders
     through the same generator, so the committed file and the fresh render move
     together and agree at their new size. The banner comes out 22% smaller and
     nothing objects. Same for SNAP, and the same argument the 1024x512 note in
     this file's header makes about HEIGHT.

     So the constants are pinned here, exactly as Play's literals are: changing
     the composition is then a two-file edit that shows up in a diff, instead of
     one character nothing sees. If you are deliberately re-proportioning the
     banner, change the generator AND this test, in a PR that says why.

     Values are the measured ones documented in build-feature-graphic.mjs: the
     mark lands 655x347 at (185, 77). */
  assert.equal(SPAN_W, 0.64, "SPAN_W");
  assert.equal(SPAN_H, 0.70, "SPAN_H");
  /* Imported by the generator from build-icons.mjs, so this also fails if the
     icons' own SNAP moves -- which is the point of sharing it. */
  assert.equal(SNAP, 12, "SNAP (shared with the icons)");
});

test("feature-graphic.png stays inside its byte ceiling", () => {
  /* Not a bundle budget -- this file is uploaded to Play and never shipped to a
     device, and Play's own limit is 15 MB. It is a blow-up detector: the ceiling
     is ~30% above the measured 96.8 KB, so a redrawn logo has room and a
     filtering regression (the icons' first generator emitted 105 KB where 47 KB
     was achievable, against a gradient exactly like this one) does not. */
  const bytes = read(OUTPUT).length;
  assert.ok(bytes <= 128 * 1024, `${OUTPUT} is ${(bytes / 1024).toFixed(1)} KB, over its 128 KB ceiling`);
});

/* ---------- the screenshots: captured, so pinned to Play's rules ---------- */

test("there are enough phone screenshots to publish, and not too many", () => {
  const shots = screenshots();
  assert.ok(shots.length >= PLAY.MIN_SHOTS, `Play needs at least ${PLAY.MIN_SHOTS} phone screenshots; found ${shots.length}`);
  assert.ok(shots.length <= PLAY.MAX_SHOTS, `Play accepts at most ${PLAY.MAX_SHOTS} phone screenshots; found ${shots.length}`);
});

test("every phone screenshot is exactly 720x1280 and inside Play's limits", () => {
  for (const file of screenshots()) {
    const { width, height, bytes } = imageSize(`${DIR}/${file}`);
    /* The exact size, not merely the ratio. A 360x640 screenshot is also 9:16
       and also legal, and would silently halve the resolution of the listing. */
    assert.equal(width, SHOT_W, `${file}: width`);
    assert.equal(height, SHOT_H, `${file}: height`);
    for (const side of [width, height]) {
      assert.ok(side >= PLAY.SHOT_MIN_SIDE, `${file}: ${side}px is under Play's ${PLAY.SHOT_MIN_SIDE}px minimum`);
      assert.ok(side <= PLAY.SHOT_MAX_SIDE, `${file}: ${side}px is over Play's ${PLAY.SHOT_MAX_SIDE}px maximum`);
    }
    assert.ok(bytes <= PLAY.SHOT_MAX_BYTES, `${file}: ${(bytes / 1024).toFixed(0)} KB is over Play's 8 MB limit`);
  }
  /* On the CONSTANTS, not on the files. Asserting `width * 16 === height * 9`
     after pinning width to 720 and height to 1280 cannot fail; asserting it here
     can, and catches the actual mistake available — someone retargeting the
     package to a size that is not 9:16. */
  assert.equal(SHOT_W * 16, SHOT_H * 9, "SHOT_W x SHOT_H must be exactly 9:16");
});

/* ---------- the copy ---------- */

/** Play counts what is in the field, and a trailing newline in a text file is
    an artefact of the file, not of the copy. Every count here strips it. */
function copy(name) {
  return text(`${DIR}/${name}`).replace(/\r\n/g, "\n").replace(/\n+$/, "");
}

test("the short description fits Play's 80-character field", () => {
  const s = copy("short-description.txt");
  assert.ok(s.length > 0, "short-description.txt is empty");
  assert.ok(s.length <= PLAY.SHORT_MAX, `short description is ${s.length} characters, over Play's ${PLAY.SHORT_MAX}`);
  /* One line. The field is single-line; a newline pasted into it is dropped
     silently, which turns two sentences into one run-on nobody proofreads. */
  assert.ok(!s.includes("\n"), "the short description must be a single line");
});

test("the full description fits Play's 4000-character field", () => {
  const s = copy("full-description.txt");
  assert.ok(s.length > 0, "full-description.txt is empty");
  assert.ok(s.length <= PLAY.FULL_MAX, `full description is ${s.length} characters, over Play's ${PLAY.FULL_MAX}`);
});

test("neither description makes a claim we cannot stand behind", () => {
  /* Play cross-checks none of this and a false claim is a real liability, so the
     ban is on the SHAPE of the claim rather than on any particular sentence:
     scale, popularity, ratings, prizes, press. Every one of these is a thing a
     later session would add in good faith to make the listing sound bigger. */
  const banned = [
    /\bmillions?\b/i, /\bthousands?\b/i, /\bhundreds\b/i,
    /\b(users|downloads|subscribers|listeners) (worldwide|and counting)\b/i,
    /\btrusted by\b/i, /\bjoin (over )?\d/i,
    /\b\d[\d,.]*\+? (users|downloads|listeners|episodes|shows|podcasts|segments)\b/i,
    /\bstar (rating|rated)\b/i, /\baward[- ]winning\b/i, /\bbest[- ]selling\b/i,
    /\bas (seen|featured) (in|on)\b/i, /\b#1\b/, /\bnumber one\b/i,
  ];
  for (const name of ["short-description.txt", "full-description.txt"]) {
    const s = copy(name);
    for (const re of banned) {
      assert.ok(!re.test(s), `${name} makes an unverifiable claim matching ${re}`);
    }
  }
});

test("neither description signals the size of the company", () => {
  /* A sweep already had to strip all of this from the website once. It is not
     modesty: it tells an acquirer, a competitor and a prospective partner
     exactly how much is behind the product, and it is impossible to walk back
     from a store listing that is mirrored everywhere. */
  const banned = [
    /\bindie\b/i, /\bsmall team\b/i, /\bsolo (developer|dev|founder)\b/i,
    /\bone-(man|woman|person)\b/i, /\bjust (two|three) of us\b/i,
    /\bwe['’]re a (small|tiny)\b/i, /\bbootstrapp?ed\b/i, /\bside project\b/i,
    /\bgarage\b/i, /\bhobby project\b/i,
  ];
  for (const name of ["short-description.txt", "full-description.txt"]) {
    const s = copy(name);
    for (const re of banned) {
      assert.ok(!re.test(s), `${name} signals company size, matching ${re}`);
    }
  }
});

test("the full description names the publisher", () => {
  /* The listing and the developer account have to agree, and "JW Labs LLC" is
     the legal name on the account. A listing that says anything else reads as a
     mismatch during review. */
  assert.match(copy("full-description.txt"), /JW Labs LLC/);
});

/* ---------- the package, as a package ---------- */

test("README.md names every asset in the directory", () => {
  /* The README is the whole deliverable for the person filling in the form: if
     an asset is in the folder and not in the README, it is invisible, and if it
     is in the README and not in the folder, they go looking for it. Both
     directions, so adding a fifth screenshot without documenting it is red. */
  const readme = text(`${DIR}/README.md`);
  const assets = fs.readdirSync(path.join(ROOT, DIR)).filter((f) => f !== "README.md");
  assert.ok(assets.length > 0, `${DIR} has no assets`);
  for (const f of assets) {
    assert.ok(readme.includes(f), `README.md does not mention ${f}`);
  }
  /* The reverse direction is scoped to THIS package's own naming, not to every
     filename in the prose. The README legitimately points at things that live
     elsewhere -- `icon-512.png` is in the repo root, because Play's 512 icon is
     the one the app already ships and copying it here would fork it. What must
     not happen is the README promising `screenshot-5-…` that nobody committed. */
  const PACKAGE_ASSET = /^(feature-graphic\.png|screenshot-\d+-[\w-]+\.(?:jpg|png)|[\w-]*description\.txt)$/;
  for (const named of readme.match(/[\w-]+\.(?:png|jpg|txt)/g) || []) {
    if (!PACKAGE_ASSET.test(named)) continue;
    assert.ok(assets.includes(named), `README.md points at ${named}, which is not in ${DIR}`);
  }
});

test("README.md's stated character counts and byte size are the real ones", () => {
  /* THE GAP THIS CLOSES was live when it was written: the README said the full
     description was 2249 characters while the file was 2247, because one
     sentence was corrected and the count was not. Nothing failed. These three
     numbers are the ones a founder reads to check they pasted the whole field —
     a wrong one is worse than no number, because it sends them looking for two
     missing characters that were never there.

     Written as the README's own phrasing rather than a bare number so the
     assertion fails if the sentence is rewritten around the number too. */
  const readme = text(`${DIR}/README.md`);
  const short = copy("short-description.txt").length;
  const full = copy("full-description.txt").length;
  const bytes = read(OUTPUT).length;
  assert.ok(readme.includes(`one line, ${short} characters`), `README.md should say the short description is ${short} characters`);
  assert.ok(readme.includes(`— ${full} characters`), `README.md should say the full description is ${full} characters`);
  assert.ok(
    readme.includes(bytes.toLocaleString("en-US")),
    `README.md should give the feature graphic's size as ${bytes.toLocaleString("en-US")} bytes`
  );
});

test("the screenshots' capture recipe is committed alongside them", () => {
  /* The one thing standing between these files and "stale artefacts nobody can
     reproduce". It has to name the deployed URL it was driven against and carry
     the harness verbatim -- a prose description of a procedure is not a
     procedure. */
  assert.ok(
    fs.existsSync(path.join(ROOT, DIR, "CAPTURE.md")),
    `${DIR}/CAPTURE.md is missing: the screenshots are committed with no recorded way to re-cut them`
  );
  const recipe = text(`${DIR}/CAPTURE.md`);
  /* This pins the GitHub Pages spelling, not `jwlabs.ai`, and that is correct
     today: Pages is where the screenshots were actually taken, and the same web
     root the Android shell bundles. The listing copy is on `jwlabs.ai` because
     that is the public marketing domain. If the deploy ever moves to the custom
     domain, this assertion needs a deliberate edit -- it failing then is the
     check working, not a bug. */
  assert.match(recipe, /jw-incorporated\.github\.io\/foray/, "CAPTURE.md must name the deployment it captured");
  assert.match(recipe, /__phone/, "CAPTURE.md must carry the viewport harness itself, not a description of it");
  assert.match(recipe, new RegExp(`${SHOT_W}\\s*[x×]\\s*${SHOT_H}`), "CAPTURE.md must state the output size it produces");
  for (const file of screenshots()) {
    assert.ok(recipe.includes(file), `CAPTURE.md does not say how ${file} was produced`);
  }
});
