/* Regenerates every app icon from ONE file: tools/brand/4a-logo.png.
   Run: node tools/brand/build-icons.mjs

   The logo will change again. Before this existed there were two icons checked
   in with no recorded ancestor, copied into dist/ and mobile/www/ by two other
   scripts, so "update the logo" meant editing binaries by hand and hoping the
   sizes agreed. Now the master is the only thing anyone edits, and
   build-icons.test.mjs fails if a committed icon stops matching what this
   emits -- so a hand-edited icon is a red build, not a silent drift.

   No dependencies: tools/brand/png.mjs does the PNG container and node:zlib
   does the compression. The repo has no image library and should not gain one
   for a task that runs when the logo changes, which is roughly never.

   The master is a WIDE wordmark (the "4a" ligature whose tail becomes a
   waveform), and app icons are square. So it is padded, never cropped: cropping
   a wordmark to a square removes letters. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { decode, encode } from "./png.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const MASTER = path.join(HERE, "4a-logo.png");
const ROOT = path.join(HERE, "..", "..");

/* Fraction of the square the wordmark spans. 0.78 keeps the mark's bounding box
   inside the circle an Android adaptive mask or a rounded iOS mask can cut: a
   1.89:1 box inscribed in a circle of diameter d is 0.88d wide, and Android's
   safe zone is the central 80%, giving 0.88 x 0.80 = 0.70 for the box corners.
   The corners of THIS mark are empty (the 4's apex and the waveform's tail), so
   0.78 sits between the two and no ink has ever fallen outside a mask. If the
   logo becomes squarer, raise it. */
const SPAN = 0.78;

/* The master is a generated image, so its "flat" cream ground is not flat: it
   drifts between (252,251,246) and (253,252,247) and carries compression noise.
   That noise is expensive, because PNG pays per unpredictable byte and the
   ground is most of the canvas. Snapping anything within this sum-of-channel
   distance of the background TO the background took the 512px icon from 59.8 KB
   to 46.9 KB, and both icons ship inside the mobile bundle.

   12 is chosen from the measured curve: 8 gives 51.1 KB, 12 gives 46.9, 20 gives
   44.2, 30 gives 43.2. Past 12 the return is under 4 KB and the risk is real,
   because a large enough threshold starts eating the anti-aliased edge where the
   ink meets the ground. Every pixel this touches is cream inside the wordmark's
   bounding box; the ink edges are tens of units away and untouched.

   EXPORTED because `tools/store/build-feature-graphic.mjs` quantises the Play
   banner with the same threshold, and a second literal 12 in that file is a
   number that can drift to 20 in one edit while this one stays at 12 — which
   would produce a banner and an icon quantised differently from the same master,
   sitting a centimetre apart in the listing. One constant, one place. */
export const SNAP = 12;

/* Every size this repo publishes, and who consumes it. Anything not listed here
   is generated by Capacitor from the native projects, which are not tracked.

   NOT THE GOOGLE PLAY STORE ICON, which this file used to claim. Play rejected
   icon-512.png -- it requires a 32-bit PNG and these are colour type 2, which
   they must stay because the App Store rejects an icon carrying an alpha
   channel. The Play listing icon is `docs/store/play/app-icon-512.png`, built
   by `tools/store/build-play-icon.mjs`, and it is cropped differently as well.
   Both facts are argued there. */
export const SIZES = [
  { file: "icon-1024.png", px: 1024 }, //   App Store marketing icon (submission only; not shipped in the bundle)
  { file: "icon-512.png", px: 512 },   //   manifest.json, App Store icon, lock-screen artwork
  { file: "icon-180.png", px: 180 },   //   apple-touch-icon, favicon
];

/* background(), inkBox() and resizeArea() are EXPORTED, not because icons need
   them exported but because `tools/store/build-feature-graphic.mjs` renders the
   Play Store's 1024x500 banner from this same master and must place the mark on
   the same ground, trimmed the same way, resampled the same way. Two copies of
   "find the cream, find the ink, area-average it down" would drift the day the
   logo is redrawn, and the drift would show as a banner whose background does
   not match the icon beside it in the listing. */

/* The mark's own background, read from the master rather than hardcoded, so a
   redrawn logo on a different ground still produces a seamless square. */
export function background(img) {
  const { width: w, height: h, data: d } = img;
  const at = (x, y) => { const i = (y * w + x) * 4; return [d[i], d[i + 1], d[i + 2]]; };
  const corners = [at(1, 1), at(w - 2, 1), at(1, h - 2), at(w - 2, h - 2)];
  return [0, 1, 2].map((c) => Math.round(corners.reduce((s, p) => s + p[c], 0) / corners.length));
}

/* Tightest box containing anything that is not the background. Trimming the
   master's own uneven margins (55 left, 58 right, 24 top, 47 bottom) is what
   makes the mark land centred instead of merely placed. */
export function inkBox(img, bg, threshold = 60) {
  const { width: w, height: h, data: d } = img;
  let x0 = w, y0 = h, x1 = -1, y1 = -1;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = (y * w + x) * 4;
      const dist = Math.abs(d[i] - bg[0]) + Math.abs(d[i + 1] - bg[1]) + Math.abs(d[i + 2] - bg[2]);
      if (dist > threshold) {
        if (x < x0) x0 = x; if (x > x1) x1 = x;
        if (y < y0) y0 = y; if (y > y1) y1 = y;
      }
    }
  }
  if (x1 < 0) throw new Error("master is uniform -- no ink found");
  return { x0, y0, w: x1 - x0 + 1, h: y1 - y0 + 1 };
}

/* Area average. For downscaling (every case here -- the master is 917 wide and
   the largest output takes 804 of it down to 799) this is the correct filter,
   not an approximation of one: each destination pixel is the mean of exactly the
   source pixels it covers. */
export function resizeArea(img, box, dw, dh) {
  const { width: sw, data: s } = img;
  const out = Buffer.alloc(dw * dh * 4);
  for (let y = 0; y < dh; y++) {
    const sy0 = box.y0 + (y * box.h) / dh, sy1 = box.y0 + ((y + 1) * box.h) / dh;
    const iy0 = Math.floor(sy0), iy1 = Math.max(iy0 + 1, Math.ceil(sy1));
    for (let x = 0; x < dw; x++) {
      const sx0 = box.x0 + (x * box.w) / dw, sx1 = box.x0 + ((x + 1) * box.w) / dw;
      const ix0 = Math.floor(sx0), ix1 = Math.max(ix0 + 1, Math.ceil(sx1));
      let r = 0, g = 0, b = 0, n = 0;
      for (let sy = iy0; sy < iy1; sy++) {
        for (let sx = ix0; sx < ix1; sx++) {
          const i = (sy * sw + sx) * 4;
          r += s[i]; g += s[i + 1]; b += s[i + 2]; n++;
        }
      }
      const o = (y * dw + x) * 4;
      out[o] = Math.round(r / n); out[o + 1] = Math.round(g / n);
      out[o + 2] = Math.round(b / n); out[o + 3] = 255;
    }
  }
  return { width: dw, height: dh, data: out };
}

/* Exported so the test can regenerate in memory and compare against the
   committed bytes without shelling out or writing to the working tree. */
export function renderIcon(master, px) {
  const bg = background(master);
  const box = inkBox(master, bg);

  /* Fit by whichever dimension binds, so this keeps working if the logo is
     redrawn taller than it is wide. */
  const scale = Math.min((px * SPAN) / box.w, (px * SPAN) / box.h);
  const dw = Math.max(1, Math.round(box.w * scale));
  const dh = Math.max(1, Math.round(box.h * scale));

  const mark = resizeArea(master, box, dw, dh);

  const canvas = Buffer.alloc(px * px * 4);
  for (let i = 0; i < canvas.length; i += 4) {
    canvas[i] = bg[0]; canvas[i + 1] = bg[1]; canvas[i + 2] = bg[2]; canvas[i + 3] = 255;
  }
  const ox = Math.round((px - dw) / 2), oy = Math.round((px - dh) / 2);
  for (let y = 0; y < dh; y++) {
    mark.data.copy(canvas, ((oy + y) * px + ox) * 4, y * dw * 4, (y + 1) * dw * 4);
  }

  for (let i = 0; i < canvas.length; i += 4) {
    const dist = Math.abs(canvas[i] - bg[0]) + Math.abs(canvas[i + 1] - bg[1]) + Math.abs(canvas[i + 2] - bg[2]);
    if (dist > 0 && dist <= SNAP) {
      canvas[i] = bg[0]; canvas[i + 1] = bg[1]; canvas[i + 2] = bg[2];
    }
  }

  return encode({ width: px, height: px, data: canvas }, { rgb: true });
}

export function loadMaster() {
  return decode(fs.readFileSync(MASTER));
}

if (process.argv[1] && process.argv[1].endsWith("build-icons.mjs")) {
  const master = loadMaster();
  console.log(`master ${path.relative(ROOT, MASTER)}: ${master.width}x${master.height}`);
  for (const { file, px } of SIZES) {
    const png = renderIcon(master, px);
    fs.writeFileSync(path.join(ROOT, file), png);
    console.log(`  ${file.padEnd(15)} ${px}x${px}  ${(png.length / 1024).toFixed(1)} KB`);
  }
}
